name: Window

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest `
            https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip `
            -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok -Force

      - name: Run ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
          Start-Process powershell `
            -ArgumentList '-NoExit', '-Command', '.\ngrok\ngrok.exe tcp 3389'

      - name: Activating RDP access
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name 'fDenyTSConnections' -Value 0

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name 'UserAuthentication' -Value 1

      - name: Change pass for RDP
        env:
          ADMINPASSWORD: ${{ secrets.ADMINPASSWORD }}
        run: |
          net user runneradmin $Env:ADMINPASSWORD

      - name: Get Ngrok Tunnel Info
        run: |
          Invoke-WebRequest http://localhost:4040/api/tunnels | Select-Object -ExpandProperty Content

      - name: Run loop
        run: |
          ping -t localhost
