name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download ngrok
        shell: powershell
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Setup ngrok auth
        shell: powershell
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

      - name: Set strong password for RDP
        shell: powershell
        run: |
          $Password = "Aa1!$(Get-Random -Minimum 1000 -Maximum 9999)"
          net user runneradmin $Password
          echo "===================================="
          echo "RDP USER : runneradmin"
          echo "RDP PASS : $Password"
          echo "===================================="

      - name: Start ngrok TCP 3389
        shell: powershell
        run: |
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow

      - name: Get ngrok tunnel info
        shell: powershell
        run: |
          Start-Sleep -Seconds 10
          Invoke-WebRequest http://127.0.0.1:4040/api/tunnels

      - name: Keep runner alive
        shell: cmd
        run: |
          ping 127.0.0.1 -t
